Skip activesupport-5.0.0 test if Ruby <= 2.2.0

diff --git a/test/run b/test/run
--- a/test/run
+++ b/test/run
@@ -1,25 +1,40 @@
 #!/bin/bash
 
+exit_status=0
 gemfile_dir=$1
-scenario=$2
 gemfile="$gemfile_dir/Gemfile"
+scenarios=$(cat $gemfile_dir/scenarios)
 
-echo
-echo "Testing scenario $scenario with $gemfile..."
-export BUNDLE_GEMFILE=$gemfile
-bundle install
-result="$(bundle exec ruby -I lib $scenario)"
+function run_scenario {
+  test_scenario=$1
 
-status=$?
-if [[ $result != "" ]]; then
-  echo 
-  echo "=> FAIL: Expected empty output but was:"
-  echo "--$result--"
-  exit 1
-fi
-if [[ $status -ne 0 ]]; then
-  echo 
-  echo "=> FAIL: Expected zero exit status"
-  exit 1
-fi
-echo "=> PASS"
+  echo
+  echo "Testing scenario $scenario with $gemfile..."
+  export BUNDLE_GEMFILE=$gemfile
+  bundle install
+  result="$(bundle exec ruby -I lib ${test_scenario})"
+
+  status=$?
+  if [[ $result != "" ]]; then
+    echo
+    echo "=> FAIL: Expected empty output but was:"
+    echo "--$result--"
+    return 1
+  fi
+  if [[ $status -ne 0 ]]; then
+    echo
+    echo "=> FAIL: Expected zero exit status"
+    return 1
+  fi
+  echo "=> PASS"
+}
+
+echo $scenarios
+for scenario in $scenarios; do
+  run_scenario "test/scenarios/$scenario"
+  if [ $? -ne 0 ]; then
+      exit_status=1
+  fi
+done
+
+exit "$exit_status"
